### ISSUE TITLE
[Request]: Autocompletion for the "From User" username filtering field in the "Advanced Search" helper dialog

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#1041]
### Describe the request

This dialog in 0.8.x is pretty cool:

![image](https://github.com/GeopJr/Tuba/assets/479401/f4fff69e-b422-4d07-be21-9e951d6fc792)

…except that the "From User" field is hard to use as it does not offer autocompletion like the message composer would.

It would be great if it did offer that at least for those I follow (or those + the ones from the social graph of people I follow), because I can never remember the crazy long Mastodon user ID handles (or even people's short usernames), and Tuba's modal single-dialog UI workflow does not permit me to look it up on the side at the same time.

Extra bonus points if it could somehow offer autocompletion in the global search field outside that dialog (when using the `from:` key, for example), too!

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I don't think I can do this right now. GtkEntryCompletion is deprecated now with a replacement planned for GTK 5. At the same time, even if it wasn't, I don't think it would allow 'dynamically' searching / only accepts pre-defined models

**Comment by nekohayo** [comment]
Hmm! Since this may be uncharted territory for the future of the autocompletion widget, maybe an alternative, for the Advanced Search dialog, could be a "person picker" sub-dialog/popover that is basically a filtering-searchable list of your followers and those you follow, that once you select one of the results, it inserts the correct text into the field?

Another stopgap low-technical-complexity measure could be to provide an example of the syntax in the field's placeholder text, but that's less convenient than a user picker popover button or autocompletion widget :)

**Comment by GeopJr** [comment]
Both sound good! I can add a whole search entry, no need to limit to people you know

**Comment by GeopJr** [comment]
I'm not entirely sure about a popover for account searching, mainly because you are already on the search page so another smaller search feels a bit repetitive/redundant

How does an 'auto-fill' button sound?

[Screencast from 2024-10-04 21-04-22.webm](https://github.com/user-attachments/assets/82876ec1-0c69-4cfa-aafc-f365dcaf3c28)

It just sends the query to the search api, so you can actually do deeper searching based on bios like:

[Screencast from 2024-10-04 21-09-32.webm](https://github.com/user-attachments/assets/b6796840-66ef-4936-9d16-ba2ac60f7628)
