### ISSUE TITLE
[Bug]: Autocomplete does not show relevant users

### ISSUE THREAD

**Issue by SimplyCorbett** [GeopJr/Tuba#1167]
### Describe the bug

Can you fix this? Image attached. Autocomplete does not show the user I'm trying to message.

### Steps To Reproduce

Try messaging a user you just talked to.

### Logs and/or Screenshots

![Screenshot from 2024-10-19 02-38-23](https://github.com/user-attachments/assets/4a64a269-19e4-43f8-83b1-79755532c8c2)

### Instance Backend

I'm not sure / Other

### Operating System

Gentoo

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.4 (1.5.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

### Additional Context

Using iceshrimp.net (not the .js)

**Comment by GeopJr** [comment]
Handle (and hashtag) auto complete works by sending the incomplete handle to `/api/v1/accounts/search` and asking it to return max 4 accounts.

This is something that can only be fixed (or rather optimized) on iceshrimp.net's side.

I'm not closing this yet however, when I get on my laptop, I want to recheck that tuba extracts the handle right, because according to your screenshot, it seems to only return people whose instances match but not their name. My suspicion is that, if tuba sends `@bea`, then iceshrimp doesn't normalize it to match its internal structure, e.g.
If users internally are saved as "[username]@[instance]" then it only matches the @[instance] part as it starts with an `@` but [username] doesn't

**Comment by GeopJr** [comment]
I'll take a look when I get on my laptop

**Comment by GeopJr** [comment]
> I'm not closing this yet however, when I get on my laptop, I want to recheck that tuba extracts the handle right, because according to your screenshot, it seems to only return people whose instances match but not their name. My suspicion is that, if tuba sends @bea, then iceshrimp doesn't normalize it to match its internal structure, e.g.
If users internally are saved as "[username]@[instance]" then it only matches the @[instance] part as it starts with an @ but [username] doesn't

I'm positive that this is the issue. Tuba searches `@bea`. Mastodon returns the same results on both `@bea` and `bea`. I assume mona does the latter, but I cannot check as it's not open source and I don't have a supported device.
