### ISSUE TITLE
Nested GtkScrolledWindow

### ISSUE THREAD

**Issue by bugaevc** [GeopJr/Tuba#1176]
### Describe the bug

I was looking at the list box / scrolled window things, and noticed that there are actually _two_ nested `Gtk.ScrolledWindow` instances in the tree:

![Screenshot From 2024-10-24 13-46-17](https://github.com/user-attachments/assets/b421e94a-dd4d-443b-bf3a-5c6dcccf4590)

Please don't do that, I don't want to even think about why this works at all :slightly_smiling_face:

### Steps To Reproduce

1. Hope to fix various issues around Tuba by hacking on `Gtk.Label`, notice things have to do with `Gtk.ListBox` and `Gtk.ScrolledWindow`
2. Open the inspector
3. Notice two nested scrolled windows
4. Stare at it in horror

### Instance Backend

Mastodon

### Operating System

Fedora Linux 41

### Package

OS repositories

### Troubleshooting information

os: Fedora Linux 41 (Workstation Edition)
prefix: /usr
flatpak: false
version: 0.8.4 (production)
gtk: 4.16.3 (4.16.1)
libadwaita: 1.6.1 (1.6.0)
libsoup: 3.6.0 (3.6.0)
libgtksourceview: 5.14.1 (5.14.0)

**Comment by GeopJr** [comment]
Is it that big of an issue?

FWIW (this is from Tootle, I can only assume for the reasons it was made like this), the nested scrolled window exists because both the timelines and the tabbed-base inherit from base (which has a scrolled window). Tabbed base is a hack around base, made to hold other bases. E.g. the explore timeline is a tabbed base with 4 timelines. Main is also one but is designed as if it's not (sidebar items => tabs on narrow window size).

#1177 removed the scrolled window from tabbed base, though unsure if it is prone to any segfaults at a glance
