### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by darkdragon-001** [GeopJr/Tuba#15]
Please [publish to Flathub](https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md).

You can take [Flathub Tootle repository](https://github.com/flathub/com.github.bleakgrey.tootle) for inspiration.

Related #13

**Comment by GeopJr** [comment]
Thanks for the suggestion, but it's not ready.

There's still a lot to do and fix that unless addressed I'm not comfortable with publishing Tooth.

You can keep track of most of them on the issues page - and while e.g. custom emojis can wait, media uploading & alt text, spoiler tags, lists, polls, crashes caused by instance instability and migrating to libsoup3 are extremely important for a complete experience.

As (partially) mentioned in that linked issue, there's already a CI set-up that builds a flatpak and uploads it on GitHub artifacts: https://github.com/GeopJr/Tooth/suites/9424603333/artifacts/445296263

You should be able to install it with:
`$ flatpak install --user ./dev.geopjr.tooth.flatpak`

I'll leave this issue open until Tooth is ready!

**Comment by GeopJr** [comment]
Unfortunately, GitHub doesn't provide direct links to latest artifacts, so you'd have to go to Actions > Select the latest successful run > Click the artifact you want to download. However, there's a third-party service called nightly.link which basically provides direct links to the latest artifact: https://nightly.link/GeopJr/Tooth/workflows/build/main/dev.geopjr.tooth-x86_64.zip

I'll see about adding it to the README!

**Comment by primalmotion** [comment]
any chance to have an ARM build? I use Tooth on a Linux phone, used to compile it myself, but latest versions does not build anymore

**Comment by GeopJr** [comment]
See: #41 

but if your problems with building it are related to the source code, feel free to [open an issue](https://github.com/GeopJr/Tooth/issues/new) with some logs!

**Comment by primalmotion** [comment]
Thanks. It works! 

the build error happens was something about missing objects about emojis in gtk4 libs. It's probably an outdated distro package

**Comment by darkdragon-001** [comment]
You can also consider publishing to Flathub Beta until it's ready: https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by GeopJr** [comment]
It's now available on Flathub https://flathub.org/apps/details/dev.geopjr.Tuba :tada:
