### ISSUE TITLE
[Request]: Indicate hyperlink selection

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#188]
### Describe the request

Environment: flatpak tuba 0.2, pureos10 - gnome 3.38 based, phosh/phoc 0.25.2, wayland, mobile phone L5, touch screen device.

Steps to repeat:
1. check post with external hyperlink, URL
2. select hyperlink, URL
3. observe it opens in default browser
4. observe on hyperlink, URL selection no tuba UI feedback is provided that selection occurred

Similar to Firefox ESR the easiest might be to just underline the hyperlink, URL upon successful selection, click temporarily. The underline can then be removed when other text is selected or another post is opened.

This is a UX improvement and gives user feedback that something has or should have occurred when selecting an actionable link.

This could probably be expanded to other tuba links that open within tuba instead of externally and keep tabs of whatever was last selected visually.

![link](https://user-images.githubusercontent.com/80182265/232150869-e12a1482-8b98-4446-bb22-e63a2f2c0078.png)

See first link is underlined as it was previously selected while other links are not.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I don't think this is something we should do, at least not the same way as the example.

GTK, just like browsers, *underline* all links which improves accessibility

[WCAG](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html):
> [1.4.1](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-without-color) Use of Color: Color is __not__ used as the __only visual means__ of conveying information, indicating an action, prompting a response, or distinguishing a visual element. (Level A)

Sites like search engines can get away with it (removing the default style) because all items are expected to be links, but when mixed with other non-link text it becomes a problem.

The default style for links in browsers *is* the same as GTK's 
![image](https://user-images.githubusercontent.com/18014039/233758026-370ba93e-a932-48e2-a8a6-024ab0ec4008.png)

> This is a UX improvement and gives user feedback that something has or should have occurred when selecting an actionable link.

Something should *always* happen when activating a link, the user doesn't need further feedback, if you've come across a situation where it didn't, please open an(other) issue!


I'll close this for now
