### ISSUE TITLE
[Request]: Keyboard navigation

### ISSUE THREAD

**Issue by sol2070** [GeopJr/Tuba#199]
### Describe the request

It would be nice if we could navigate with standard keys like PgDn, PgUp, Up, Down etc. I know that you can do that after hitting Tab sometimes, but PgDn only advances one post (acting in the same way as the Down key); and if you interact with some post with the mouse, the keys stop working.

Thank you for this software!

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
Keyboard navigation would be nice. The usual `k` and `l` to go to the next/previous post, `b` to boost, `r` to reply and so on. 

I think Semaphore has the best keyboard timeline navigation I've seen in any Fediverse client.

![Zrzut-ekranu-z-2023-04-21-23-12-33](https://github.com/GeopJr/Tuba/assets/121253127/54b86bec-a56e-476c-9e1e-b0367904818a)

**Comment by mattiasb** [comment]
There's a bunch of keybindings in the GNOME HIG that are pretty good to take a look at. See [here](https://developer.gnome.org/hig/reference/keyboard.html).

I'm personally mostly missing `Ctrl+n` for composing a new message. But `Ctrl+w` for closing the current window (be that a compose popup or the main window) and I see that `Ctrl+q` doesn't work when the compose popup is open. Also `Alt+HOME` doesn't navigate to the start state of the application.

**Comment by GeopJr** [comment]
Addressed some of the suggestions on #303

> It would be nice if we could navigate with standard keys like PgDn, PgUp, Up, Down etc. I know that you can do that after hitting Tab sometimes, but PgDn only advances one post (acting in the same way as the Down key); and if you interact with some post with the mouse, the keys stop working.

While I did add it, it might have issues with accessibility and will be reverted if any are raised.

> Keyboard navigation would be nice. The usual k and l to go to the next/previous post, b to boost, r to reply and so on.

I'd rather avoid using non-utility keys without a modifier for keyboard navigation for the same reasons as the <kbd>Ctrl</kbd><kbd>Return</kbd> issue, it's too easy to trigger accidentally and in general over-complicated for something 1-2 tabs away[1]. Some of the shortcuts from the screenshot sound interesting however and worth looking into

[1]: for example, for the <kbd>Ctrl</kbd><kbd>Return</kbd> one in the composer, Tuba has to listen to *every* keypress just in case it gets triggered

> I'm personally mostly missing Ctrl+n for composing a new message. But Ctrl+w for closing the current window (be that a compose popup or the main window) and I see that Ctrl+q doesn't work when the compose popup is open. Also Alt+HOME doesn't navigate to the start state of the application.

<kbd>Ctrl</kbd>+<kbd>T</kbd> was already being used for composing new posts but <kbd>Ctrl</kbd>+<kbd>N</kbd> does make more sense. I've added the other shortcuts to the composer too (composer would use <kbd>Esc</kbd> already since it's a 'dialog'), but keep in mind there are some special conditions for the composer that won't allow it to close unless the content is not valid or empty (so users don't accidentally lose all their progress).
