### ISSUE TITLE
[Bug]: When clicking the not-first image in a group of images, it first shows the 1st image then scrolls to the image you wanted

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#206]
### Describe the bug

Basically as the title says ;) in a group of image thumbnails, when you click, say, the 2nd or 3rd one, it doesn't expand directly the one you clicked, it shows and loads the 1st one, wastes about 1 second doing so (and shows a spinner), and then scrolls to the one you clicked and wanted to see.

It's cute, but the delay and animation instead of "going directly to what I wanted to see" everytime gets tiresome pretty quickly.

### Steps To Reproduce

1. In a group of image thumbnails in a mastodon toot (such as [this one](https://mastodon.online/@Escritos_mano/110187285645533884)), click the 4th one

### Logs and/or Screenshots

Although you can't see the mouse cursor, [this video](https://user-images.githubusercontent.com/479401/233764256-3ff809a1-bea6-447b-ba14-2b1250a01c76.webm) shows what happens with the reproduction step above.

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
I think the main annoyance is that it takes 1 second to start scrolling - and that's a hack/workaround for a bug.

https://gitlab.gnome.org/GNOME/libadwaita/-/issues/597
https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/827

Basically, the carousel won't scroll to a widget that hasn't been yet allocated so following the issue example, I added a 1 second timeout.

Disabling the animation seems a bit off (probably because of the delay):

[Screencast from 2023-04-22 16-10-40.webm](https://user-images.githubusercontent.com/18014039/233787876-81b7cb13-b69f-4998-824a-3926e290d257.webm)

Lowering the timeout to 250ms feels much more natural but I'll have to do a bit more investigation:

[Screencast from 2023-04-22 16-11-42.webm](https://user-images.githubusercontent.com/18014039/233787910-1ba8fa8a-08c6-4f98-a482-bf2fff30e05e.webm)

The bug has been fixed upstream so this is temporary anyway

**Comment by nekohayo** [comment]
Well, even if you turn GTK animations off using the GNOME Control Center's "Reduce Animations" accessibility settings, it still loads the 1st image, waits 1 second, then loads the image you actually wanted to see. This seems counterproductive in terms of UI flow, and potentially wasteful in terms of bandwidth if it actually loads two images instead of one (?)

**Comment by GeopJr** [comment]
> Well, even if you turn GTK animations off using the GNOME Control Center's "Reduce Animations" accessibility settings, it still loads the 1st image (and waits 1 second as per your animation bug mitigation scheme), then loads the image you actually wanted to see...

As mentioned in the original comment, the delay **is needed** at the moment as a workaround for that bug. Without the delay it will always show the first image no matter which one you selected.

After the fix lands in a release of libadwaita, there won't be a delay or scroll, it will open the selected image right when you select it.

> Why is it showing the 1st image at all, instead of going directly/only to the one I clicked?

> directly

(I'll use some GTK terms) When constructing the Carousel, it inserts the widgets (which are either Picture or Video) based on the post's attachment positions (3rd attachment => 3rd carousel item). Afterwards it sets the Carousel position to the one selected (which is done by calling `scroll_to` on the carousel (don't let its name trick you, you can disable the animation)).

When adding this feature, I did attempt many alternative routes with no success:

- Setting the selected attachment as the first carousel item so we avoid the whole scrolling situation - Broke the logic flow of the attachments (like if a post had 4 scanned pages of a document as attachments, move page 3 to the front would make users confused as the next page would be 1 (3 => 1 => 2 => 4)).
- Adding the selected attachment first and later inserting the rest around it - Didn't work, carousel still starts at the first page and not the first added widget.

(I can always be missing something, these are the ones I tried at the time)

> only to the one

It's part of #147

plus,
> and potentially wasteful in terms of bandwidth

it matches Mastodon's (web) client: opening a single attachment loads them all in a similar carousel-like style. I do understand both cases:

- When the user wants to see all attachments, loading each one when you scroll to it is going to be annoying instead of loading them all at once
- When the user wants to see a single one, loading them all is wasteful and might make loading the one they wanted to see take longer

but I'm leaning towards the first one as it's more common

**Comment by nekohayo** [comment]
Aaaah, I see, makes sense. Good to know that the intended behavior (barring upstream bugs) was to directly show the intended image. I had thought only the delay was the workaround for the bug you mentioned.

Thank you for the clarification!
