### ISSUE TITLE
[Request]: Ask the user for confirmation when closing a non-empty editor window

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#263]
### Describe the request

Tuba doesn't ask the user if they are sure they want to close the editor w/o sending an already written post, and I've lost several posts because of that and my own carelessness :)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by nekohayo** [comment]
I believe a better way would be to autosave the contents and to restore them the next time you invoke the composer (or maybe show an InfoBar with a preview of the old contents and offer to restore them), rather than to prompt for the "are you sure".

The autosave approach would also have the advantage of offering protection against outages (network or power), computer crashes, the user needing to quit the app/logout for some reason, etc.

**Comment by LukaszH77** [comment]
I like your idea. Phanpy does it like that and it works well. 

![Zrzut ekranu z 2023-05-20 23-04-51](https://github.com/GeopJr/Tuba/assets/121253127/11211f25-dfc1-4b73-bdb3-6bbfccfc4c84)
