### ISSUE TITLE
Performance (scrolling): 0.3.0 worse than 0.2.0

### ISSUE THREAD

**Issue by brunnerm4x** [GeopJr/Tuba#267]
First of all: Thanks  for making and maintaining this application! 
Unfortunately i noticed that the new version (0.3.0 installed from flathub) works slower (when scrolling it seems like ~5fps), interaction is more or less possible, but no fun ...

**Comment by nekohayo** [comment]
Not specific to the Librem5, I'm also seeing this on a desktop workstation with open source Radeon graphics, on a triple-buffered Wayland GNOME 44 session. I would suggest retitling the ticket to reflect that this is not specific to the phone hardware.

Here's a sysprof capture of what happens simply by scrolling the comments up and down repeatedly in [this thread](https://mastodon.social/@GeopJr@tech.lgbt/110397978665949280) (for example) : [tuba-0.3.0-scroll-perfs-issue-capture.zip](https://github.com/GeopJr/Tuba/files/11522631/tuba-0.3.0-scroll-perfs-issue-capture.zip)

![tuba-0 3 0-scroll-perfs-issue-sysprof](https://github.com/GeopJr/Tuba/assets/479401/2fab63ef-d725-4bae-bb73-cc8876c9cdc2)

**Comment by alexreid** [comment]
I've not measured it, but scrolling is noticeably worse on my system, too (Fedora 38, Gnome 44.1 Wayland, Intel UHD 620 GPU)

**Comment by kdwk** [comment]
This is almost certainly due to Tuba using the Cairo renderer instead of GL by default
![Screenshot from 2023-05-21 10-17-12](https://github.com/GeopJr/Tuba/assets/39268094/8c9e031b-6342-467c-9dfc-aa68aba5fa49)

**Comment by GeopJr** [comment]
Thanks for the pointers! Cairo was used to fix #197 but nobody noticed any performance issues then, I'll make another patch release

**Comment by nekohayo** [comment]
Can confirm that 0.3.2 that landed through Flathub now scrolls smoothly. Thank you!

I presume the hyperlinks underline issue is something that will simply have to wait to depend on a stable GTK release that would feature the fix...

**Comment by Saltane** [comment]
Reviving the issue, because overall performance on my side isn't good at all. *I think* it belogs here.

### Tuba overall works increasingly worse the more posts were loaded. I recorded a video of this performance hit.

https://github.com/user-attachments/assets/4c5df048-e62f-4bc3-a668-0e2fc1435755

(ignore nothing showing up when clicking dots on the post, OBS didn't record that)

Many posts were loaded at this point. You can see how laggy scrolling is (except when **not** hovering over posts, as shown at the beginning), hovering over entries on the left, interracting with buttons, switching timelines, accounts, opening up modal windows (settings, *about* window), changing window's size are increasingly laggy as well. Performance gets bad faster on Akkoma backend compared to Mastodon/Chuckya (not sure if posts per load count is the reason). Does not seem to be network issues, because no amount of waiting changes this.

Chuckya, Akkoma, and Sharkey backends tested, with all suffering from this issue.

Don't find anything interesting in log when running Tuba from CLI without additional arguments. It does a lot of this though:

```
(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:54:10.138: Trying to snapshot TubaWidgetsEmoji 0x64f9cfc254f0 without a current allocation

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:54:10.140: Trying to snapshot TubaWidgetsEmoji 0x64f9ee023e10 without a current allocation

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:54:10.140: Trying to snapshot TubaWidgetsEmoji 0x64f9ee09a1b0 without a current allocation

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:54:10.157: Image.vala:69: Failed to download image at "https://pl.m0e.space/proxy/4wLQLqych7yk6vKge1p1k6emd58/aHR0cHM6Ly9tZWRpYS5taXNza2V5dXNlcmNvbnRlbnQuY29tL2Vtb2ppL2FibG9iY2F0d2F2ZS5hcG5n/ablobcatwave.apng": Нерозпізнаний формат файлу зображення

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:54:48.928: MarkupView.vala:410: Unknown HTML tag: "center"

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:54:49.212: MarkupView.vala:410: Unknown HTML tag: "small"

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:54:50.077: Image.vala:69: Failed to download image at "https://pl.m0e.space/proxy/EXeu5jtkFkO2hywQMQ1z47Q2HaU/aHR0cHM6Ly9tZWRpYS5taXNza2V5dXNlcmNvbnRlbnQuY29tL2lvL2Y1YzJjMTQ2LTMzNDAtNGVlOS1hNDA5LTRhMmU5MGRkYmMzYS5hcG5n/f5c2c146-3340-4ee9-a409-4a2e90ddbc3a.apng": Нерозпізнаний формат файлу зображення

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:54:50.762: Trying to snapshot TubaWidgetsEmoji 0x64fa1236b950 without a current allocation

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:55:02.126: Trying to snapshot TubaWidgetsEmoji 0x64fa4472a400 without a current allocation

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:55:02.630: Image.vala:69: Failed to download image at "https://pl.m0e.space/proxy/ptyGnN5iWqnF_12rDXhBzSm4gfs/aHR0cHM6Ly9tZWRpYS5taXNza2V5dXNlcmNvbnRlbnQuY29tL2Vtb2ppL2FibG9iY2F0Y3J5aW5nY3V0ZS5hcG5n/ablobcatcryingcute.apng": Нерозпізнаний формат файлу зображення

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:55:30.214: Image.vala:69: Failed to download image at "https://pl.m0e.space/proxy/KjDC9Bxna1XfS2QKEVPC13cySlU/aHR0cHM6Ly9jZG4ubWFzdG8uaG9zdC9mbG9zcy9tZWRpYV9hdHRhY2htZW50cy9maWxlcy8xMTMvNjc2LzczNi82NDIvNDQzLzE0NS9vcmlnaW5hbC83ZGQwYzJkODUyOTRhYzU1Lm1wNA/7dd0c2d85294ac55.mp4": Нерозпізнаний формат файлу зображення

(dev.geopjr.Tuba:2): Tuba-WARNING **: 09:56:08.818: Image.vala:69: Failed to download image at "https://pl.m0e.space/proxy/GcnSNYuQJVgq0mb9Kou8i3YcYE8/aHR0cHM6Ly9tZWRpYS5taXNza2V5dXNlcmNvbnRlbnQuY29tL2lvL2VjZjZjNzVlLWU5NGItNDMwMC1hZTBmLTQ2YmM1NjBkNjdlNC5wbmc/ecf6c75e-e94b-4300-ae0f-46bc560d67e4.png": Критична помилка зчитування файлу зображення PNG: bad adaptive filter value

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:56:12.001: Trying to snapshot TubaWidgetsEmoji 0x64fa696d08c0 without a current allocation

(dev.geopjr.Tuba:2): Gtk-WARNING **: 09:56:12.003: Trying to snapshot TubaWidgetsEmoji 0x64fa6ebdd2a0 without a current allocation
```

Changing renderer with `GSK_RENDERER` to ngl, gl, and vulkan does no noticeable effect.

### Diagnostics:

```
os: GNOME 47 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.9.0 (production)
gtk: 4.16.7 (4.16.7)
libadwaita: 1.6.2 (1.6.2)
libsoup: 3.6.1 (3.6.1)
libgtksourceview: 5.14.2 (5.14.2)
libspelling: true
Clapper: false
GStreamer: GStreamer 1.24.9 (1.9.24.0)
```

**Comment by GeopJr** [comment]
Your issue is partially ListBox vs ListView (https://github.com/GeopJr/Tuba/issues/179 https://github.com/GeopJr/Tuba/issues/500 https://github.com/GeopJr/Tuba/pull/504 https://github.com/GeopJr/Tuba/issues/410) and partially this https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2172

It has nothing to do with this issue. This issue was about cairo.
