### ISSUE TITLE
[Request]: Rendering of incoming Markdown

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#288]
### Describe the request

With the growing popularity of Markdown supporting platforms, it would be useful if Tuba could properly display posts from them.  
And I'm not talking about crazy Calckey animations, but the basics such as:

*Italic*
**Bold**
***Bold italic*** 
~~Strikethrough~~
`Code` 
```
Code
blocks
```

There are some other, more advanced syntax elements that would be nice to have, but not so necessary:

[links](https://tuba.geopjr.dev/) 

# headings (to keep it clean and simple, all headers should have the same font size)

* unordered 
* lists
  * nested ones too

1. ordered
2. lists

> quotes

and 

> block
>
> quotes

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'm not sure if this is something we should do. Basically, the author's server and yours decide what they should render and clients consume them (usually) as html. This is why when you see for example a \*key post with animations and whatnot from a Mastodon instance, all you see is the emojis used - not the MFM. Another example would be the post in #229; since mastodon.social supports blockquotes, you were able to see it and so could Tuba, but I couldn't from my instance since it doesn't have blockquote support yet, lets compare what the API returns:

from my instance:

```html
<p>\n<p>SpaceX Crew-2</p>\n<p>SpaceX Crew-2 was the second operational flight of a Crew Dragon spacecraft, and the third overall crewed orbital flight of the Commercial Crew Program. The mission was launched on 23 April 2021 at 09:49:02 UTC, and docked to the International Space Station on 24 April at 09:08 UTC.</p>\n</p>\n<p>\n<p>Wake-up calls</p>\n<p>NASA began a tradition of playing music to astronauts during the Gemini program, and first used music to wake up a flight crew during Apollo 15. Each track is specially chosen, often by the astronauts' families, and usually has a special meaning to an individual member of the crew, or is applicable to their daily activities.[20]</p>\n</p>\n<p>\n<p>Day 2: An off-key, all flute comedic cover of A-Ha's "Take On Me", made by YouTube artist "Shittyflute".[21] A-ha (original) - Shittyflute (Cover) - Thomas Pesquet\n<a href="https://en.wikipedia.org/wiki/SpaceX_Crew-2" class="" rel="nofollow noopener noreferrer" target="_blank">https://en.wikipedia.org/wiki/SpaceX_Crew-2</a></p>\n</p>\n<p>A HA - TAKE ON ME - SHITTYFLUTED:\n<span class=""><a href="https://www.youtube.com/watch?v=nF7lv1gfP1Q" rel="nofollow noopener noreferrer" target="_blank">https://www.youtube.com/watch?v=nF7lv1gfP1Q</a></span></p>\n<p><a href="https://karab.in/tag/astronomia" class="hashtag" rel="nofollow noopener noreferrer" target="_blank">#astronomia</a></p>\n
```

notice the lack of `<blockquote>` elements

and now from mastodon.social:

```html
<blockquote>\n<p><strong>SpaceX Crew-2</strong></p>\n<p>SpaceX Crew-2 was the second operational flight of a Crew Dragon spacecraft, and the third overall crewed orbital flight of the Commercial Crew Program. The mission was launched on 23 April 2021 at 09:49:02 UTC, and docked to the International Space Station on 24 April at 09:08 UTC.</p>\n</blockquote>\n<blockquote>\n<p><strong>Wake-up calls</strong></p>\n<p>NASA began a tradition of playing music to astronauts during the Gemini program, and first used music to wake up a flight crew during Apollo 15. Each track is specially chosen, often by the astronauts' families, and usually has a special meaning to an individual member of the crew, or is applicable to their daily activities.[20]</p>\n</blockquote>\n<blockquote>\n<p>Day 2: An off-key, all flute comedic cover of A-Ha's "Take On Me", made by YouTube artist "Shittyflute".[21] A-ha (original) - Shittyflute (Cover) - Thomas Pesquet\n<a href="https://en.wikipedia.org/wiki/SpaceX_Crew-2" class="" rel="nofollow noopener noreferrer" target="_blank">https://en.wikipedia.org/wiki/SpaceX_Crew-2</a></p>\n</blockquote>\n<p>A HA - TAKE ON ME - SHITTYFLUTED:\n<span class=""><i></i><a href="https://www.youtube.com/watch?v=nF7lv1gfP1Q" rel="nofollow noopener noreferrer" target="_blank">https://www.youtube.com/watch?v=nF7lv1gfP1Q</a></span></p>\n<p><a href="https://karab.in/tag/astronomia" class="hashtag" rel="nofollow noopener noreferrer" target="_blank">#astronomia</a></p>\n
```

When *your* server returns strikethrough, italic, bold, blockquote etc elements, then Tuba should render them as expected, here's an Akkoma markdown post:

![Screenshot from 2023-05-27 10-32-49](https://github.com/GeopJr/Tuba/assets/18014039/95977c71-936e-47df-9dd8-2ccc4757646a)

And last but not least, it can change user intent. On Akkoma, you can choose whether your post is Plain text, Markdown, HTML etc. That means it's up to the author to choose whether

```
>.<
```
should render as

>.< 

or

\>.<

Letting the client decide how to render can also cause *other* issues: I believe *key does that (or did that, I don't know), where Mastodon users would use \*\*\*TEXT\*\*\* for attention but would render as violently shaking text from *key's side (making it impossible to read if it was too long)

I think some of them are harmless (like replacing \* with a bullet) but others need to be careful consideration

**Comment by LukaszH77** [comment]
OK, now I understand better what's going on, thanks. :)
