### ISSUE TITLE
[Feature Request]: Unable add a pixelfed.de account

### ISSUE THREAD

**Issue by arturasb** [GeopJr/Tuba#318]
### Describe the bug

I was trying to add my pixelfed.de account to the app, but it ended with "Bad request" message

### Steps To Reproduce

1. Open Tuba
2. Select Switch Account then Add Account
3. Enter pixelfed.de to the Server URL
4. Pixelfed.de will open in Firefox, enter credentials and pixelfed.de will show the Authorize Tuba page.
5. Click Allow
6. Tuba will show "Server returned an error" popup with "Bad request" message.
7. Alternative flow:
8. From the error select "try manual authorization", then enter prepared before hand authorization token, click next but Tuba will show the same as in No 6.

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

I'm not sure / Other

### Operating System

Fedora Workstation 37

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.2 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by LukaszH77** [comment]
I don't think Pixelfed accounts are currently supported. You need to use Pixelfed's web client for that.

**Comment by arturasb** [comment]
Then this is misleading:
![image](https://github.com/GeopJr/Tuba/assets/35307455/5df5fb47-9f48-41f5-b9c4-73cec59eddc6)

Specifically, as the Pixelfed is a Fediverse platfom:

> like Mastodon, GoToSocial, Akkoma & more!

**Comment by arturasb** [comment]
> (you wouldn't expect Tuba to act as a Peertube or Lemmy client, would you?)

To be fair I expected  Tube to support those too, well because it supports "Fediverse protocol" :)

Thank you for explaining different variations of the protocol, it makes sense. Maybe the app description update would help to adjust expectations more accurately. And given this situation, this not a bug.

And if you do not mind considering adding Pixelfed support, that would be awesome improvement of Tuba. Could this bug be converted to a feature request then ?

**Comment by GeopJr** [comment]
Yeah, no problem!

Just to explain a bit more how the whole "fediverse" thing works:

All fediverse platforms are able to 'talk' to each other using ActivityPub (the protocol), so for example you can watch PeerTube videos from your Mastodon account and comment on them by replying to the post. However, these platforms have different features and use cases. Lemmy/Kbin are reddit-like, so a client for them would have to have a similar UI to reddit (or their web clients). PeerTube is youtube-like, a client would need to display videos in a grid and of course allow users to upload videos/start livestreams, not create text-based posts. A Mobilizon client would have no use for favorites, boosts, bookmarks, polls, emojis, etc.

To be honest, even "for popular microblogging Fediverse platforms like..." is misleading because you can't really support all of them, Tuba, Tusky, Elk, etc. support the Mastodon API (which is by no means standard, but other microblogging platforms have chosen to support it to avoid having to create different clients for each one). Misskey, for example, *doesn't* support the Mastodon API, even though it is also a microblogging platform, but Pixelfed (somewhat) does, even though it is not.

**Comment by arturasb** [comment]
All right. It seems that there is a common set of functions for almost all ActivityPub-enabled clients. Maybe that could lead to a client, which only reads, posts, comments and follows/unfollows in major types of Fediverse platforms Without event trying to implement each and every platform specific stuff. Imagine Tuba becoming a Linux app which will aggregate my microbloging, picture and video blogging feeds in one app at very basic - ActivityPub - level.... Just an idea ;-)

**Comment by LukaszH77** [comment]
You can have all these feeds in Tuba right now. I follow multiple Pixelfed and PeerTube accounts, and their post show up on my Mastodon timeline in Tuba.

You just can't create any post types other than microblog.

**Comment by arturasb** [comment]
> You can have all these feeds in Tuba right now. I follow multiple Pixelfed and PeerTube accounts, and their post show up on my Mastodon timeline in Tuba.

Yes, I know I can follow myself in a different Fediverse platform. But maybe I could do more :)

**Comment by LukaszH77** [comment]
> Yes, I know I can follow myself in a different Fediverse platform. But maybe I could do more :)

Not just yourself. You can follow anyone on any federated server.
