### ISSUE TITLE
[Request]: Large font size reflected in the whole app

### ISSUE THREAD

**Issue by mahdi1234** [GeopJr/Tuba#340]
### Describe the request

Having hidpi laptop enabling "Large font size" was first thing to do.

However it only changes fonts for toots not the rest of the app. Would expect to have it changed everywhere. Ideally specify exact font size would be even better, but that's different topic.

gentoo / lxqt / 0.3.2

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
That option is meant for the timelines only since there's a lot of text and can be overwhelming, if you need the whole app to have a larger font size, then your best bet is to set it from your host's settings. On GNOME it's under Settings > Accessibility > Large Text, unsure about lxqt (probably lxappearance):

Tuba with host's "Large Text" disabled:
![image](https://github.com/GeopJr/Tuba/assets/18014039/78b58f22-dc67-4253-ac96-f80e4c2c3b72)

Tuba with host's "Large Text" enabled:
![image](https://github.com/GeopJr/Tuba/assets/18014039/bdbdb416-76c7-46cb-8029-d7a20ad96e9f)

P.S. It hasn't landed on a release yet but Tuba's Large Font setting is using a pre-defined size which might be smaller than the system's 'Large Font'. This has been fixed on main and will land in the next release.

I'll leave this open until it's resolved but I don't think that should be a per-app change, chances are all GTK apps' font size will need to be increased

**Comment by bragefuglseth** [comment]
I agree, this probably shouldn't be an in-app setting, since it's possible to acheive using the Large Text preference in Settings.
