### ISSUE TITLE
[Request]: Rewrite with Rust

### ISSUE THREAD

**Issue by johnlpe** [GeopJr/Tuba#350]
Could we someday rewrite this with Rust? Just an idea far into the future and low priority.

**Comment by GeopJr** [comment]
There is definitely room in the Linux world for more Fediverse clients (especially with the amount of servers and client apis out there), but I'm not that interested in rewriting Tuba 
into another language. I won't turn down a PR though 🤷

At the same time, there aren't that many advantages to rewriting it in Rust, other than maybe using a crate for the API instead of having to keep track of both it and the GUI (and fewer occasional memory leaks / segfaults of course). Vala's memory management & familiar syntax allowed me to move quickly without having any prior experience with it. 

Otherwise, I'd point you to https://gitlab.gnome.org/World/Social, which may be maintained again in the future.

**Comment by johnlpe** [comment]
> There is definitely room in the Linux world for more Fediverse clients (especially with the amount of servers and client apis out there), but I'm not that interested in rewriting Tuba into another language. I won't turn down a PR though 🤷

Yes, there definitely is room, but if I could get this client written in Rust it would be the best of them all. IMO Rust is faster, better memory handling, better libraries and more developers.

> Otherwise, I'd point you to https://gitlab.gnome.org/World/Social, which may be maintained again in the future.

Thanks!

**Comment by GeopJr** [comment]
This is probably not the best place to start a language war and while I agree with most of your points, I want to be clear, in case any Tuba users stumble upon this, that Tuba's performance is not limited by Vala in any way. Vala 'compiles' to efficient C code. Rust's performance gains would a lot more appealing if Tuba was written in a language like Python.
