### ISSUE TITLE
[Request]: Reply/thread indicators shown in the main timeline

### ISSUE THREAD

**Issue by eobet** [GeopJr/Tuba#374]
### Describe the request

No posts in the main timeline have any reply/thread indicators. You just see a lot of posts without context scroll by. Only when you click on a post do you get a vertical grey line drawn to indicate replies/threads.

It would be more helpful if those vertical grey lines could also be drawn in the main timeline (or some other similar indicators), until Mastodon gets better methods to filter out replies in the main timeline (since a general issue with Mastodon is that you often also end up reading them in reverse chronological order, making their context even more problematic to understand).

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
The thread line is for connecting threads and doesn't make sense in a reverse chronological order, so probably something like this is more appropriate:

![image](https://github.com/GeopJr/Tuba/assets/18014039/a8b8125d-a224-4928-ad1d-ad2a02934967)

**Comment by tio-trom** [comment]
Why not do it like Friendica does it? Something like this:
![2023-09-07_04-19](https://github.com/GeopJr/Tuba/assets/38043315/a1cdf0d4-37d9-4876-9b08-e4dddb2bd1f2)
Where the home-feed displays posts without replies. And posts have comments (thus replies). This way the newsfeed is less cluttered and sane. Instead of seeing random replies that make no sense without a context, you can see posts only.

So I suggest an option that displays "posts only" and no individual replies. This is what prevents me from using these applications, because they copy the style of Mastodon and Mastodon, in my view, is hellish confusing :D when it displays random "Cool video" "Great job" or whatever messages out of context.
