### ISSUE TITLE
[Feature]: When the server does not accept a post and user cannot publish a post add the means to save it as a draft to post it later when the server is back up.

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#418]
### Describe the feature

Sometimes a toot cannot be published due to a variety of issues, such as server is not accepting toots.

### Steps To Reproduce

1. in tuba select post button
2. write post
3. add poll
4. select publish

Observe nothing happens.

5. save the draft post
6. add menue item to select previously saved draft post
7. publish draft post later

Observe post is published.

### Logs and/or Screenshots

```
os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.4 (4.10.3)
libadwaita: 1.3.3 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)
```
![Screenshot from 2023-07-29 14-54-19](https://github.com/GeopJr/Tuba/assets/80182265/a53760b4-f389-43e8-b5c8-a0f0c7690d2b)

### Instance Backend

I'm not sure / Other

### Operating System

Ubuntu 23.04

### Package

Flatpak

### Troubleshooting information

NA

### Additional Context

In these instances maybe it would be good to allow a post to be saved as a draft to be published later when the server is back up.

**Comment by GeopJr** [comment]
Thanks for raising this issue! I'm going to need some logs (`flatpak run dev.geopjr.Tuba`, follow your steps and observe the logs after you press publish)

**Comment by CaptainMorgan12** [comment]
Now it works, I think it is related to the server maybe not a tuba issue after all. But there is no error, or warning it just doesn't do anything before. I do see a few warnings:

`<pre>(dev.geopjr.Tuba:2): Tuba-<span style="color:#A2734C"><b>WARNING</b></span> **: <span style="color:#12488B">15:33:52.793</span>: Streams.vala:114: DISCONNECTED: https://social.librem.one/api/v1/streaming/?stream=direct. Reconnecting in 6 seconds.
Tuba-<span style="color:#26A269"><b>Message</b></span>: <span style="color:#12488B">15:33:52.793</span>: Streams.vala:118: Closing stream: https://social.librem.one/api/v1/streaming/?stream=direct
Tuba-<span style="color:#26A269"><b>Message</b></span>: <span style="color:#12488B">15:33:59.368</span>: Streams.vala:68: Opening stream: https://social.librem.one/api/v1/streaming/?stream=direct
</pre>`

**Comment by GeopJr** [comment]
Oh, the librem.one instance. Purism seems to be having some server issues at the moment that might be the reason it wouldn't go through.

drafts (well, scheduled posts, but it includes drafts too) are tracked on #142
Displaying the error to the user should totally be implemented, I'll get to it as soon as possible!

To be honest, I'm not that fond of the librem.one instance's software, it's running a custom fork of Mastodon 3.1.1(?) which is missing some features such as hashtag following, setting languages and probably post editing, and might be vulnerable to some of these https://github.com/mastodon/mastodon/security (unless the hosted version is not the one on https://source.puri.sm/liberty/host/smilodon)

Those logs are websocket related, I haven't checked (and considering source.puri.sm is down right now, I can't) but since dms have been removed from the fork, Tuba might be trying to connect to a socket that doesn't exist, I'll check it out too.

**Comment by CaptainMorgan12** [comment]
Thanks ok so my post is duplicate of #142 feel free to close, as of the notification no issue notification is posted not sure there is a user story for that?

**Comment by CaptainMorgan12** [comment]
Interesting when creating a post without a poll, then trying to edit the post with the poll there are some issues. Only the "Edit" button shows not the publish.

Either again server related or another bug?
![Screenshot from 2023-07-29 15-59-12](https://github.com/GeopJr/Tuba/assets/80182265/af609a71-b476-4981-bf77-2795fc12500a)

**Comment by GeopJr** [comment]
It's backend software related, since librem.one is running a Mastodon fork before post editing was implemented, Tuba is trying to send the edit but the server returns 404 (Not Found). The button on the dialog shows you what action will happen when you press it, in this case it will "edit" your post (/ not "publish" a new one)
