### ISSUE TITLE
[Request]: User avatars / profile pictures images in desktop notifications on flatpak

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#426]
### Describe the request

I noticed now that the mastodon web interface includes the avatar of users boosting/favoriting/etc. your toots, but Tuba only shows its symbolic logo icon. When not in data saver mode, wouldn't it make sense to include the avatars in the desktop notification (and fallback to the tuba icon when in data saver mode or when no avatar is available)?

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
They got removed from the flatpak version as of c65d95cc92d61d1659d4c0fcf2b1b94f135719d2

For some reason I haven't had the time to debug yet, when there are icons in the notifications on Flatpak, the notifications would never show up. Icons do show up on non-flatpak environments

**Comment by nekohayo** [comment]
I asked the GNOME hackers hivemind, and their remark regarding to the solution for the problem is: "`file://` URI can never work" and "use `GBytesIcon`". I hope that helps.

**Comment by GeopJr** [comment]
**I might be wrong**, but I don't think either of these apply here:

This is the code for the icons:
```vala
var icon_file = GLib.File.new_for_uri (account.avatar);
var icon = new FileIcon (icon_file);
toast.set_icon (icon);
```
(toast is a `GLib.Notification`)

account.avatar is an `https://` url to the actor avatar (e.g. `https://files.mastodon.social/cache/accounts/avatars/107/389/604/296/011/399/original/a46710c15bced1b0.png`)

so the only options are:
1) Downloading the file and using it with GBytesIcon etc which is probably not appropriate as all notifications will be delayed until the icon is done (since notifications cannot be modified once sent (`Modifying notification after this call [GLib.Application#send_notification] has no effect`))
2) The current solution (`GLib.File.new_for_uri` => `FileIcon`)

My issue is that it doesn't work *only* in flatpak. Here's what it looks like when built from source:

![Screenshot from 2023-09-07 00-53-57](https://github.com/GeopJr/Tuba/assets/18014039/f403a5c2-6216-4611-a608-74cf790876f4)


My only suspicion was gvfs but even after giving the flatpak the permissions it still didn't work and it's difficult to debug since everything just fails silently
