### ISSUE TITLE
[Request]: In notifications and post statistics, show the number of followers a boosting person has

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#493]
## User story

I find myself wanting to be able to conveniently see "in real time" the spread or social impact of my writings on Mastodon. It is very tedious to have to click each boost's user profile manually to see how many people XYZ person is presumably sharing the post with. If I am going to have to do it manually anyway, why not automatically provide this information for convenience?

Having such statistics is very motivating and encourages me to write better content for the fediverse, which I was previously apprehensive of doing, as someone used to the wide reach of mainstream social networks.

## Possible ways to solve this

I would suggest that this information gets shown near the end of the notification text in the "Notifications" tab and the desktop notification balloons, so that instead of only saying "Bob boosted your post", maybe say something like "Bob boosted your post to %d followers"

(Yes, this is not a "guarantee" or anything, but for most intents and purposes this is the most straightforward way to say it, unless you want to put stuff in parentheses, or use wording such as "reshared" instead of "boosted"...)

Additionally, in the "Boosted by" statistics view feature:
* Sort the users there by number of followers
* Show a clear visual of each users' number of followers (ex: with some encircled "colored rounded pill"-style label on that list widget, instead of the user's join date on the top-right of each person listed).
* There could also be an additional "summary" part to that statistics view, showing a summary label with something like:  
"At least **32** users boosted/reshared this post to a total of **435** (or more) followers."  
(presuming there aren't really other statistics beyond that)
* Ideally, this should get updated / refreshed automatically with sorted insertion

Even with an improved detailed statistics view, I would still want the number of followers to be shown in the boost notifications though :)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I can see two conflicting sides to this already :/ (for the same reasons as the post interaction buttons stats). Some people left traditional social media to *escape* the constant "ranking" of interactions based on popularity etc and some other people (and businesses) needing them to see what kind of content is more popular etc.

I don't think there should be an option just for this either. Maybe as a tooltip on hover?

Coincidentally, I played with popovers today (#495) which might be the best middle ground solution for this. What do you think?

> Sort the users there by number of followers

Not possible. Like most things on the API, there's pagination and no sorting options. So it can end up looking like this:

500 followers
10 followers
0 followers
--- scrolled down enough to fetch the next page ---
1000 followers
5 followers
1 follower

> Show a clear visual of each users' number of followers (ex: with some encircled "colored rounded pill"-style label on that list widget, instead of the user's join date on the top-right of each person listed).

I think mastodon does it somewhat right, though we do show the user's description too :thinking:

![image](https://github.com/GeopJr/Tuba/assets/18014039/d327de5c-4f41-46fc-b7ee-bdec702f1355)

> There could also be an additional "summary" part to that statistics view, showing a summary label

1. Just like the other one, pagination kills this. If there's a post with 400 boosts, Tuba would need to do 5 separate requests just to get the full list of users (and they take some time at 80 entries per request)
2. 99% of the time there will be some overlap so the number will be inaccurate (if two people have the exact same 4 followers and they both boost your post, only 4 people will see them not 8 (otherwise, getting all their followers would fall under the previous argument, they are paginated too))

---

I **really** don't think Mastodon (and especially the API) was made with this use case in mind at all :/ I'd rather see an API endpoint for "analytics" that are calculated server-side than a server-spammy inaccurate client-side attempt at it. (<-- This is not about showing the amount of followers someone has, but about the 'X users shared with Y users' request)

**Comment by nekohayo** [comment]
OK so sorting and "summarized statistics" are technically impossible... I guess this is why we can't have extra-nice things™ ;) but the rest of the ideas would already be a good improvement.

* I agree Mastodon's presentation in the screenshot above is nicer than what we currently have for the "Favorited by" and "Boosted by" lists, because when you have more than 4-5 items in there those lists benefit from being much more compact, instead of showing the full bio and unrelated dates; the full bio could be shown on hover maybe (perhaps with your popover idea). And in the compact view, you could show whether or not that person follows your account. Even if not sorted by followers count, this would already help a little to be able to scroll up/down the list and get a "glance" of the repartition of the propagation.
* I still think the followers count in the notification strings would be really neat to have for the real-time aspect of this (instead of needing to go dig into the stats view, and then those things don't auto-refresh...)

I think the theoretical concern that "providing numbers ruins the game for some people" is overblown. If some users don't care about numbers indicating the repartition of the reach of their post comes from, then they can just visually ignore that part of the notification... and if a tiny minority of users actively wants to avoid numbers because they don't want to feel any "excitement" about their posts being appreciated, I would say that anything—numbers or not—would overwhelm them, and that I'd expect they will probably just turn off notifications entirely anyway 🤷

**Comment by GeopJr** [comment]
I think this is somewhat done with the right click popups:

![image](https://github.com/GeopJr/Tuba/assets/18014039/3c52aae5-a0f6-47c2-9153-fcf26ee4c3f5)

and the profile cards

![image](https://github.com/GeopJr/Tuba/assets/18014039/979a617f-48f8-49f8-a6d1-a5f9c2507445)


Though the popover doesn't display the followers, but I'll add that
