### ISSUE TITLE
[Request]: Refresh button in titlebar

### ISSUE THREAD

**Issue by nanopone** [GeopJr/Tuba#494]
### Describe the request

It seems there is no way to refresh a feed without pulling down, which is awkward and not user-friendly for someone with only a mouse. Putting a refresh button in the title bar in the empty space on the left is an easily understandable way to refresh the feed the user is looking at. I made a mockup of what this could look like: 
![image](https://github.com/GeopJr/Tuba/assets/49787675/0e44aff4-4a8e-4ebc-90aa-38f0f314f627)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by Commenter25** [comment]
I agree, swiping is a very uncommon action with a mouse, and it does not actually scroll the feed otherwise, so there's little reason to assume that would work. Though personally, I feel swiping to refresh isn't very obvious even for a mobile device. It's ingrained into memory because it's the standard paradigm, but if you weren't aware the app did that and/or weren't conditioned to assume it by other apps, there is no visual indication anywhere you can refresh outside of the keyboard shortcuts, which obviously aren't accessible on a touch screen.

I haven't investigated, so I could be wrong, but it seems like it would also cause trouble for assistive technology using non-standard mouse input, such as eye tracking for motor disabilities. They might have difficulty refreshing this way.

**Comment by GeopJr** [comment]
Thank for the suggestion!

Headerbar items don't really match the current desktop mockups so I put it in the sidebar menu, it might change in the future

![image](https://github.com/GeopJr/Tuba/assets/18014039/e1c4ee1e-858e-4b21-855a-0cafa1d2bf6b)
