### ISSUE TITLE
[Bug]: Within a user bio and metadata, profile links to accounts on other instances get opened in a browser instead of Tuba

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#499]
### Describe the bug

Sometimes, @ profile links present in bios don't get handled properly at all by Tuba; they get opened by the external web browser, instead of simply showing the linked profile within Tuba.

### Steps To Reproduce

Two example scenarios:

* View [this profile](https://mobiliteactive.org/@martinhamel) in Tuba, and try to click on @martinhamel's secondary account ("J'ai un compte généraliste à ...") link within the main bio text
* View [this profile](https://mastodon.social/@sophie@floss.social) in Tuba, and try to click the alternate user account link in the "Personal" metadata field (the 4th extra links row thingy)

...in both cases, it opens their secondary accounts' profiles into my external web browser, on their instance instead of mine, making it infuriatingly impossible to follow them without going back and remembering to do a search query instead.

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.1 (production)
gtk: 4.10.4 (4.10.4)
libadwaita: 1.3.3 (1.3.3)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
The first one is a Tuba issue (I use a different widget, I'll fix it ASAP!) but the second one (profile fields) should work. The reason it doesn't from your instance is because weirder.earth has strict moderation and your instance (mastodon.social I assume), is suspended. Tuba defaults to opening in the browser when resolving fails

**Comment by GeopJr** [comment]
Actually, on a second look, the profile description is also correct (widget-wise). Looks like the first profile has a deep-link causing instances to not be able to resolve it:

The [at]martinhamel[at]mastodon.top link in the first account's description leads to `https://mobiliteactive.org/@martinhamel@mastodon.top` when it should be leading to `https://mastodon.top/@martinhamel`

This is what happens when you click a link:

- if the object that holds the text provided a `mentions` list (usually posts), it first checks if the link exists in that list and opens it if it does
- else if the url contains `/tags/`, assume it's a hashtag and deal with that
- else if the url contains "@" or "user" (or the secret aggressive-resolving dconf option is enabled), it attempts to resolve it (by searching for it on the instance)
- else it opens it in the browser

You can go ahead from your instance and search for `https://mobiliteactive.org/@martinhamel@mastodon.top`, notice there's no results and then search `https://mastodon.top/@martinhamel` and see it pop-up

I'll close this as there's nothing I can really do to be honest :shrug:
