### ISSUE TITLE
[Bug]: code blocks are missing their content

### ISSUE THREAD

**Issue by daenney** [GeopJr/Tuba#574]
### Describe the bug

The content of the code blocks isn't being rendered. Opening the same post in a different client does render the content inside the code blocks.

### Steps To Reproduce

1. Search for post: https://social.treehouse.systems/@marcan/111160426488046610
2. Try to view it

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:34:09.446: Network.vala:34: GET: https://ap.dny.social/api/v2/search?resolve=true&q=https%3A%2F%2Fsocial.treehouse.systems%2F%40marcan%2F111160426488046610

(dev.geopjr.Tuba:2): Gtk-WARNING **: 17:34:10.870: Failed to set text 'for (int sample = 0; sample <= 127; sample++)' from markup due to error parsing markup: Error on line 1 char 38: “=” is not a valid character following a “<” character; it may not begin an element name

(dev.geopjr.Tuba:2): Gtk-WARNING **: 17:34:10.870: Failed to set text 'for (int sample = 0; sample < 127; sample++)' from markup due to error parsing markup: Error on line 1 char 38: “ ” is not a valid character following a “<” character; it may not begin an element name

(dev.geopjr.Tuba:2): Gtk-WARNING **: 17:34:10.873: Failed to set text 'for (int sample = 0; sample <= 127; sample++)' from markup due to error parsing markup: Error on line 1 char 38: “=” is not a valid character following a “<” character; it may not begin an element name

(dev.geopjr.Tuba:2): Gtk-WARNING **: 17:34:10.873: Failed to set text 'for (int sample = 0; sample < 127; sample++)' from markup due to error parsing markup: Error on line 1 char 38: “ ” is not a valid character following a “<” character; it may not begin an element name
```

![Screenshot from 2023-10-01 17-35-47](https://github.com/GeopJr/Tuba/assets/569574/99ae802e-4ac5-46b6-bc3b-b50100f422a0)

### Instance Backend

GoToSocial

### Operating System

Arch Linux

### Package

Flatpak

**Comment by valpackett** [comment]
In https://social.treehouse.systems/@AsahiLinux/111198789454694923 actually the *first* line got displayed which was really confusing :D Same bug right?

**Comment by GeopJr** [comment]
Nope, *sigh*, libxml apparently treats `mkdir /tmp/firmware<br>cd /tmp/firmware<br>mv /path/to/appleh13camerad .<br>sudo tar xzf /boot/efi/asahi/all_firmware.tar.gz <br>sudo tar czf /boot/efi/asahi/all_firmware.tar.gz .<br>sudo asahi-fwupdate<br>` as multiple children and when getting the parent's content, only returns the first one

**Comment by valpackett** [comment]
Ohh. XML is not HTML, of course… though I'm not sure what would be the least bothersome way to use a safe HTML parser from Vala :/

**Comment by GeopJr** [comment]
libxml *is* an html parser too (despite its name), well, HTML <= 4 only. This is an interesting project https://gitlab.gnome.org/World/html2pango but honestly it won't get rid of libxml for Tuba as we need more control over it.

In general there's a lot to clean up between backends, for example, Pleroma does not use `<br>` elements on newlines but rather `\n` with `white-space: pre-wrap;`, while Pixelfed uses both (sometimes next to each other like `\n<br>\n<br>`!). Then on Mastodon, the newlines sometimes end up in the wrong elements, for instance the previous post with #595 will have an extra newline *in* the blockquote 
![image](https://github.com/GeopJr/Tuba/assets/18014039/90a77d69-c1fe-4bfb-8ead-d4939f748a07)
because it's `<br>sudo asahi-fwupdate<br></code></pre><p>That's it!` when - at least IMO - the last newline should have either been outside the `<pre>` element or not exist at all.
