### ISSUE TITLE
Support displaying cropped images with focal points

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#576]
On the official web app you can set a focal point for images, which is cool to draw attention to specific parts of the image when it's cropped (e.g. in this case the top part is more interesting than the center):

![image](https://github.com/GeopJr/Tuba/assets/1908896/d5d0a015-e301-4ccd-80a3-eafd130e0c21)

**Comment by nekohayo** [comment]
Yup, that's issue #173 which also has some technical reference details ;)

**Comment by GeopJr** [comment]
I'll split them into two issues, this one about displaying them and the other one about setting them since they are different implementation wise.

The main issue with implementing this is that Gtk.Picture is sealed (cannot be subclassed) so the only way to change the way the image is displayed (outside of the predefined options (cover, content fit etc)) is by re-creating Gtk.Picture from scratch (or at least that's my understanding of the situation)

**Comment by bertob** [comment]
> outside of the predefined options (cover, content fit etc)

Might be worth filing a GTK issue asking if this could be in scope to be added to GtkPicture in the future?

**Comment by GeopJr** [comment]
I'll investigate our other GtkPicture needs further first to see if we actually do need more than GtkPicture can provide (specifically, sizing/aspect ratio (#180), animated images (#196, #435) (I believe the aspect ratio one does require more control over the widget))

**Comment by nekohayo** [comment]
I'd suggest retitling this ticket to "Support displaying cropped images with focal points" to avoid confusion with the editing part (#173).
