### ISSUE TITLE
[Bug]: Flashing Follow Requests

### ISSUE THREAD

**Issue by bleakgrey** [GeopJr/Tuba#58]
### Describe the bug

"Follow Requests" is initially visible in the app sidebar. Then the timelines are done loading and there are no pending follow requests, the item becomes hidden.

Perhaps this place should be hidden by default, becoming visible only when there are active requests.

### Steps To Reproduce

1. Open the app
2. Observe the visibility of "Follow Requests" in the sidebar

### Instance Backend

Mastodon

### Operating System

Pop!_OS 22.04 LTS

### Package

Flatpak

### Troubleshooting information

flatpak: false
version: main-15b8f4a (development)
gtk: 4.8.4 (4.8.4)
libadwaita: 1.2.1 (1.2.1)
libsoup: 2.74.2 (2.74.2)

**Comment by GeopJr** [comment]
It becomes hidden because your account is not private. I'm not sure what the best solution would be because if someone's default account is private and "follow requests" was hidden by default, they would be annoyed that it shows up instead. Should:

- it be hidden by default and only show up on private accounts?
- it be visible by default and only hide on public accounts?
- it be visible for both?
- it only be visible when there are follow requests?
