### ISSUE TITLE
[Bug]: unable to choose all post options on mobile

### ISSUE THREAD

**Issue by primalmotion** [GeopJr/Tuba#65]
### Describe the bug

The window to post a new toot is not really mobile friendly. that would be ok, but it actually prevent to send private message as it is out of the bound of the screen, without possibility to scroll

See screenshot

### Steps To Reproduce

use a linux mobile
write a toot
try to select some options
you can't

### Logs and/or Screenshots

![2023-01-27-145403](https://user-images.githubusercontent.com/208711/215221397-a1f49ac0-f577-451f-80b3-14264c1c73bd.png)

### Instance Backend

I'm not sure / Other

### Operating System

pureos

### Package

Flatpak

### Troubleshooting information

flatpak: true
version: main-78a183f (development)
gtk: 4.8.3 (4.8.3)
libadwaita: 1.2.1 (1.2.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'm not sure if it's a phosh issue, but it should have have moved to the top :/ I'll see what I can do but in the meantime, as a workaround, try to move the dialog to the bottom of the screen (if possible) so it triggers:

![A screenshot of the gtk tooth app in mobile and dark mode with the "compose post" dialog open. The dialog has moved to the bottom of the screen so the visibility dropdown is above the button instead of below it (as it doesnt fit)](https://user-images.githubusercontent.com/18014039/216130939-1fcb50fb-f2d0-4d62-8252-2a9564b0079c.png)
