### ISSUE TITLE
[Bug]: In German, screen is cut off when window has small width

### ISSUE THREAD

**Issue by tronta** [GeopJr/Tuba#665]
### Describe the bug

When set to German language, the screen gets cut off in small window sizes/mobile:

![Bildschirmfoto vom 2023-11-26 08-04-35](https://github.com/GeopJr/Tuba/assets/5135577/612a983e-04e3-4397-be29-d74730c9e0d0)

[Bildschirmaufzeichnung vom 2023-11-26, 18-08-58.webm](https://github.com/GeopJr/Tuba/assets/5135577/b6a4621c-ae83-4474-b295-dc04f71c7784)

### Steps To Reproduce

1. Switch to Geman
2. open on mobile, or resize screen to minimum

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Fedrora Silverblue 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.5.0 (production)
gtk: 4.12.3 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.3 (3.4.3)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by camelCaseNick** [comment]
The label “%lld voted” was literally translated to “%lld haben abgestimmt”. I have changed it to “%lld Stimmen" (literally "%lld votes”). Soon, Weblate should push my change. Additionally, I think #695 would be great to avoid this kind of issues in the future, because an ellipsized and thus truncated string is far less disruptive than a complete UI shift making parts of it unreachable.
