### ISSUE TITLE
[Bug]: User profile statistics (such as followers count) not updated until app restart

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#674]
### Describe the bug

If you leave Tuba running (without suspending the computer etc.) and you gain some new followers while it is running, you get the notifications for those followers but Tuba does not update the counters in your user profile, so you have a mismatch between Tuba and the Mastodon web UI, as seen in the screenshot below.

### Steps To Reproduce

1. Gain more followers
2. ???
3. ~PROFIT~ Open the PROFILE!

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/479401/6dfed63f-764e-4d04-8b6c-728ea6981147)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.5.0 (production)
gtk: 4.12.3 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.3 (3.4.3)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by GeopJr** [comment]
Has been (or at least should be) fixed by #616 

Context: Tootle did caching manually based on reference counting rather than what the server asked. That means that as long as the account object is not freed from memory or manually removed from the cache, it will stay the same. That led to some headaches with stuff like profile editing and pinning statuses. #616 leaves cache up to libsoup instead which is based on the server, if the server asks, either time based or with etags
