### ISSUE TITLE
[Request]: Square avatars

### ISSUE THREAD

**Issue by UnderEu** [GeopJr/Tuba#757]
### Describe the request

I want the option to use square avatars instead of round ones. It's a matter of personal preference and, in some cases, there are images that the round frame crop details from them.

Example: 
![Untitled](https://github.com/GeopJr/Tuba/assets/16519758/5e89d9f8-6328-4fe6-b846-f3da67d44378)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'm sorry but I'm going to have to decline.

Square avatars do not match the adwaita stylesheet (https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Avatar.html) so even if I wanted to maintain yet another option (I don't), it could break at any moment.

> in some cases, there are images that the round frame crop details from them.

You can still open images in the media viewer by clicking on them.

> I want the option to use square avatars instead of round ones. It's a matter of personal preference

You can override the libadwaita stylesheet on your machine but beware that it can break at any point, will affect other apps and that you shouldn't report issues to any project that might have been caused by it:

```sh
$ echo ".ttl-flat-button.circular,.ttl-status-avatar-actor,.ttl-status-avatar-border,avatar{border-radius:0}" >> ~/.config/gtk-4.0/gtk.css

# If you use the flatpak:
$ flatpak override --filesystem=xdg-config/gtk-4.0:ro dev.geopjr.Tuba --user
```

**Comment by UnderEu** [comment]
> You can override the libadwaita stylesheet on your machine but beware that it can break at any point, will affect other apps and that you shouldn't report issues to any project that might have been caused by it:
> 
> ```shell
> $ echo ".ttl-flat-button.circular,.ttl-status-avatar-actor,.ttl-status-avatar-border,avatar{border-radius:0}" >> ~/.config/gtk-4.0/gtk.css
> 
> # If you use the flatpak:
> $ flatpak override --filesystem=xdg-config/gtk-4.0:ro dev.geopjr.Tuba --user
> ```

That's fine for me.
