### ISSUE TITLE
[Request]: Pronouns next to username

### ISSUE THREAD

**Issue by tsbarnes** [GeopJr/Tuba#774]
### Describe the request

The latest version of Fedilab added support for displaying a users pronouns next to their name, it checks for a user field named "Pronouns" and uses the contents.
I'd love to see this in Tuba.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I wanted to this for a while but don't really know where to place them and how ellipsizing will work

I've split it into 4 options:

1. Account popovers #495 - it shows all fields

![image](https://github.com/GeopJr/Tuba/assets/18014039/771e2c50-5d19-4b30-bfdf-94c7666256c4)

2. Overlay icon with tooltip or popover on click

![Screenshot from 2024-02-05 03-05-29](https://github.com/GeopJr/Tuba/assets/18014039/5341e46c-d8d9-4d53-9436-0710f7373678)

3. Overlay label - nope, would suck on lengthy fields

![Screenshot from 2024-02-05 03-07-47](https://github.com/GeopJr/Tuba/assets/18014039/b27d5840-7227-46b7-8e74-7e50c1593109)

4. Append to name or handle - it will have to be ellipsized or might look bad

![Screenshot from 2024-02-05 03-09-19](https://github.com/GeopJr/Tuba/assets/18014039/0427dff0-c6d8-4826-9801-4721539e4022)


![Screenshot from 2024-02-05 03-10-14](https://github.com/GeopJr/Tuba/assets/18014039/c628718e-8b52-4fda-aff2-5b53f533cd1a)


I'm not sure about fedilab but megalodon does the 4th option and ellipsizes the name. The problem is that the pronouns field might contain a lot more info e.g. location or the pronouns in different languages. So ellipsizing the name could turn out to just `...` if the field is too long. Ellipsizing the handle is a no-go due to impersonation concerns 

I'm personally leaning towards the first 2

**Comment by tsbarnes** [comment]
Option 1 is probably the best user experience out of the first two.

**Comment by bragefuglseth** [comment]
It would be great to have l10n support for this as well, it could e.g. check for both "pronouns" and the localized version of the string, or even for the localized string in all available languages (if not too resource heavy).
