### ISSUE TITLE
Question about proxy handling in Tuba

### ISSUE THREAD

**Issue by danialbehzadi** [GeopJr/Tuba#788]
Hey,

If I set HTTP proxy from GNOME control center, Tuba will use it correctly and there is no problem.

As I use my email with GNOME Online Accounts, I can't set HTTP proxy constantly, because it will fail to connect to IMAP server, so I decided to pass HTTP proxy as an environment variable to tuba.

The problem is when I do this, the result is nondeterministic. Sometimes it will use the proxy and sometimes not.

I'm using this in `.desktop` file:

    Exec=env http_proxy="http://127.0.0.1:7070" env https_proxy="http://127.0.0.1:7070" env HTTP_PROXY="http://127.0.0.1:7070" env HTTPS_PROXY="http://127.0.0.1:7070" tuba %u

I also tried using Flatpak version like this:

    flatpak run --env=https_proxy="http://127.0.0.1:7070" --env=HTTPS_PROXY="http://127.0.0.1:7070" --env=http_proxy="http://127.0.0.1:7070" --env=HTTP_PROXY="http://127.0.0.1:7070" dev.geopjr.Tuba

**Comment by GeopJr** [comment]
Proxy is 100% handled by [libsoup](https://gitlab.gnome.org/GNOME/libsoup)

In the past a feature request was brought up for in-app proxy settings. I personally am against that. I don't think every single app should handle (and maintain) the proxy itself - we might as well add the entirety of GNOME Settings to every single app. However, since this is causing issues, I might take another look into it.
