### ISSUE TITLE
[Bug]: Offline dialog pops up randomly over other apps

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#969]
### Describe the bug

I noticed that I sometimes get this dialog when unlocking the session, totally out of nowhere over other, unrelated apps. First I thought it was a system thing, but it seems like it's a non-modal dialog from Tuba:

![image](https://github.com/GeopJr/Tuba/assets/1908896/19c7bd59-95ff-4da0-84c1-b28561813a85)

Modal-ness aside, I feel like a dialog is the wrong pattern for this, I'd use a banner instead, like e.g. Fractal does.

### Steps To Reproduce

1. Open the app
2. Suspend computer
3. Wake it back up
4. Unlock
5. There's this dialog, because the network has not connected yet

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

**Comment by GeopJr** [comment]
It should be a modal but I think I also need to present the main window since it can show up without user interaction (so it shows up behind it).

> I feel like a dialog is the wrong pattern for this, I'd use a banner instead, like e.g. Fractal does.

Not opposed to it but my thought process was that since nothing works without an internet connection (except than whatever timeline was open), users shouldn't interact with Tuba at all.

If it becomes a banner instead, what would happen when a user opens settings for example? Settings do network requests both when you open the window and when you close it (to save the server-side related ones). Allowing the user to change those while offline, might lead to them not being synced or be wrong.

**Comment by bertob** [comment]
> Not opposed to it but my thought process was that since nothing works without an internet connection (except than whatever timeline was open), users shouldn't interact with Tuba at all.

I think it depends on the feature. I definitely should be possible to browse the posts you have locally, and maybe composing posts and saving them to publish later could be an option. But of course, other options probably don't make sense, so maybe the relevant buttons/menu items should be disabled?

**Comment by GeopJr** [comment]
![image](https://github.com/GeopJr/Tuba/assets/18014039/6b2d3ddb-3d0e-45be-a84e-bbd7254d9863)

Should it be on the sidebar or the view? And is 'Offline' enough? Or should it be 'No Internet Connection'?

If it's on the view, it has to be on *every* view, even new and old ones. But it's visible when the sidebar is collapsed.

If it's on the sidebar, it's in a single consistent place. But it's not visible when it's collapsed.

**Comment by bertob** [comment]
Fractal only does it on the sidebar, so maybe that's good enough as a start? Alternatively we could also add it on all views, but not sure if that gets too annoying...
